In [2]:
import numpy as np
import time

In [2]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
t1 = time.time()
c = np.dot(a, b)
t2 = time.time()
print(c)
print("Vectorization time " + str(1000*(t2-t1)) + "ms")

c=0
t1 = time.time()
for i in range(1000000):
    c += a[i]*b[i]
t2 = time.time()

print(c)
print("For loop time " + str(1000*(t2-t1)) + "ms")

250033.76156441472
Vectorization time 95.45516967773438ms
250033.76156441087
For loop time 684.8568916320801ms


#### Vectorizing decreases the time for executing by lot

In [3]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


#### cal.reshape(1,4) no need because cal already in (1,4)
### No. of columns should be same for operations
## Broadcasting - automatically adjust no of rows/ columns

In [6]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [7]:
sum = A+100
print(sum)

[[156.  100.  104.4 168. ]
 [101.2 204.  152.  108. ]
 [101.8 235.  199.  100.9]]


## Never use rank 1 arrays give both rows & columns while declaring array

In [22]:
a = np.random.randn(5)
a

array([ 0.38791515,  0.06798377,  0.62912774,  0.26894883, -1.42254116])

In [23]:
a.shape

(5,)

In [24]:
a.T

array([ 0.38791515,  0.06798377,  0.62912774,  0.26894883, -1.42254116])

In [25]:
print(np.dot(a, a.T))

2.646858477071279


In [26]:
a = np.random.randn(5,1)
a

array([[-1.59796099],
       [ 0.5616228 ],
       [ 0.82236361],
       [-0.567342  ],
       [-1.79172032]])

In [27]:
a.shape

(5, 1)

In [28]:
a.T

array([[-1.59796099,  0.5616228 ,  0.82236361, -0.567342  , -1.79172032]])

In [29]:
print(np.dot(a, a.T))

[[ 2.55347933 -0.89745133 -1.31410497  0.90659038  2.86309918]
 [-0.89745133  0.31542017  0.46185816 -0.3186322  -1.00627099]
 [-1.31410497  0.46185816  0.67628191 -0.46656141 -1.47344559]
 [ 0.90659038 -0.3186322  -0.46656141  0.32187694  1.01651819]
 [ 2.86309918 -1.00627099 -1.47344559  1.01651819  3.21026171]]


In [21]:
assert(a.shape == (5,1))

In [33]:
a=np.random.randn(3,3) 
a.shape 

(3, 3)

In [34]:
b=np.random.randn(2,1)
b.shape 

(2, 1)

In [35]:
c = a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,1) 

In [36]:
a=np.random.randn(1,3)
b=np.random.randn(3,3)

In [38]:
c = a*b
c.shape

(3, 3)

In [40]:
x = np.array([1,2])
y = np.array([[1,2],
             [3,4]])

In [45]:
z= np.dot(x,y)
z

array([ 7, 10])

In [46]:
z = x*y
z

array([[1, 4],
       [3, 8]])

In [42]:
a=np.array([[2,1],[1,3]])
print(a*a)

[[4 1]
 [1 9]]


In [44]:
a=np.array([[1,1],[1,-1]])

b = np.array([[2], [3]])
c = a + b
c

array([[3, 3],
       [4, 2]])

In [3]:
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True) 

In [6]:
B.shape

(4, 1)

In [8]:
B

array([[0.91515191],
       [0.8226574 ],
       [1.33946585],
       [0.9421661 ]])

In [10]:
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
print(y.shape)

(4,)


In [11]:
x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)
print(y.shape)


(1, 2)
